engines:
  pep8:
    enabled: true

  radon: 
    enabled: false
  
  duplication:
    enabled: true
    config:
      languages:
      - python:

ratings:
   paths:
   - "**.py"

exclude_paths:
- "Procfile"
- "*.md"
- "*.txt"
- "*.yml"
- "*.ttf"
