version: "2"

plugins:
  pep8:
    enabled: true

  radon: 
    enabled: false

  duplication:
    enabled: true
    config:
      languages:
      - python:

exclude_patterns:
- "Procfile"
- "*.md"
- "*.txt"
- "*.yml"
- "*.ttf"
