engines:
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
      E111:
        enabled: false
      E114:
        enabled: false

  radon: 
    enabled: false
  
  duplication:
    enabled: true
    config:
      languages:
      - python:

ratings:
   paths:
   - "**.py"

exclude_paths:
- "Procfile"
- "*.md"
- "*.txt"
- "*.yml"
- "*.ttf"
